{% set name = "python-telegram-bot" %}
{% set version = "13.15" %}
{% set sha256 = "b4047606b8081b62bbd6aa361f7ca1efe87fa8f1881ec9d932d35844bf57a154" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - httpx >=0.23.1,<0.24

test:
  imports:
    - telegram
    - telegram.base

about:
  home: https://github.com/python-telegram-bot/python-telegram-bot
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE.lesser
  summary: A pure Python interface for the Telegram Bot API.

  description: |
    This library provides a pure Python, asynchronous interface for the Telegram
    Bot API. It's compatible with Python versions 3.7+.
    In addition to the pure API implementation, this library features a number of
    high-level classes to make the development of bots easy and straightforward.
    These classes are contained in the telegram.ext submodule.  doc_url: https://python-telegram-bot.readthedocs.io/en/stable/
  dev_url: https://github.com/python-telegram-bot/python-telegram-bot

extra:
  recipe-maintainers:
    - mdraw
