travis:
  secure:
    BINSTAR_TOKEN: e/3f5i7O2K9FDvKyxDFTdjSg4ZZ3qALDTfSlbojQOeqQfQVdejyv0aDpwHr2nKJ3oGH1GnVZbCCs0tMlRbd3+SDtiTlnxD2SCkJ1CcdyA6/DYnaPX5VH2ujOkjyOyUlP2U5crxqfJmSqN8tV4IZpZq6xI/k+LVrsPBnuSj8P2ukN6ryL2noQ7Ryy9YDIyhEjnB46mFojwVakijwwe8SGfBLxEesgsMRGCv5E3luR44v3aTjv4axbm6DSs1Dnr2ixyjDFXpbu+gCRu+ijR0xHrFpmKsTEGmtUcioHkgb9y74LHDQprZEscrL3/GxRFrO8NVwiEr+RjXgHZTb//P5uXGz+rhMLrGcrUpxLnzCNW3Pi51ZUuiElnxITar+QnrQLWaE1CyNE/Pze5hRHQuLrPEEc8YGwjR/TaQVGpXCUxCpdveC+ACp0xfgv0GgjHgtudBwmmIOjQQbYFIQimnl3RZDvjWuaDh1QOQj384SFotsI1yagI9psQJ8+eaFt2Wcbm19QbYJ3Sp10GAGSwlHgJYGdBqmZUNETBEcumWNla1n9JWWNTSNITmkWiP/5xli/4W+Omd7dvh6JmQMWVkybH7YJDuHQZVNvLDKJUqm93YJwVWBZKpa+Eq5M4ADuV0FGGnemS3Fh/bhyn3hIitI8BlPz0FrlJU3UxONysc/9Qw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
