travis:
  secure:
    BINSTAR_TOKEN: UKtZOdR33TD4a4CWchhO+d1feKAsENCfUcpWVBK2fkDdLFORGO0yk9oEGwLY8b+N0pWazBi2La/xD7bO5qaksYfvlV5AS81XsWHKWY51b2fVQmqe6JzAUQvRx7UG1Y6jd6TU9eYFN8/J7Q8GpDbwGqYaE0hnD2KQ9w/8MrAUxF7XbHWwylUJE7FVNsmodim4RVppCxrm6eMBvO5DR+7iQCOUZY7ntvqIiMvXA3y1ueGyah27XDBxObhOcpDo0xzTFO+Y++gapAi9b0cVTCLwFzKKigZroOpsDKNaQB571r00bWXN9S0I1OtnbztClVVlzNYkjNdy5qU9WarCor2MRsuK/4reVoxSkY25SXnrmVmSAH1QbZ/j9eHrUU0gKSQwgGIf7UAFR/fSrn/9fggiHpuZXkYRL2uxlwtXdh5PnddO/jfgcfwiDKN5HQikdBQ55TuXGUxcA8EMK+duhLZ5CzFYYrVVRcznM/D/C8T7bWjJGFyXzGArs/2K09JUGajg3wY5VjT6lHC9bPtt2JQHaqujxWSHjFlKDRD9DT6pspH9c8DHy7yocmjI23czIktuQBp9xH7SfDPJdm8ulqJHr72hXOv5soi2Cy8Qi1Alxwhf8f1LRP4VOfF2ZiEbw4pzXCPcJV0NWCryRI/Sv50dDkZnOc/VOde0YN4eNZvTokA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
